# -*- coding: utf-8 -*-
"""color_channels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zuj-hG1yeBtRZ9j-xEuDsCm1jHRJIFv
"""

# Think of import cv2 as opening a special toolbox for your Python programs. This toolbox is filled with \n amazing tools that let your computer "see" and understand images and videos, \n just like you do!

import cv2

# Bringing Your Images to Life: How to See What Your Code Does! in Google colab

from google.colab.patches import cv2_imshow

# That's where the magic of from google.colab import files comes in! This little line of code acts like a special doorway, letting you easily upload files directly from your computer into your Colab notebook. Think of it as a quick and simple way to bridge the gap between your computer and the online environment.

from google.colab import files

# Unlocking Image Power: Loading Your First Picture with Just One Line of Code!

image = cv2.imread('/content/RGB.webp')

# Breaking Down Image Colors: Meet the Red, Green, and Blue Teams!

blue, green, red, = cv2.split(image)

# Your Image's DNA: How Colors are Made (and Split!)

cv2_imshow  (image)
cv2_imshow(blue)
cv2_imshow(green)
cv2_imshow(red)